Project = ibsspatch
ProductType = tool
Install_Dir = /usr/local/bin

CFILES = iboot_patcher.c ibootsup.c patch.c util.c

Extra_CC_Flags = -Wall 
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
