Project = img3maker
ProductType = tool
Install_Dir = /usr/local/bin

CFILES = img3maker.c

Extra_CC_Flags = -Wall 
Extra_LD_Flags = -dead_strip

include $(MAKEFILEPATH)/CoreOS/ReleaseControl/BSDCommon.make
